<a href="https://colab.research.google.com/github/ramesh0805/Major/blob/main/Copy_of_b_Code_CreditScoring.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Importing libraries & functions





In [1]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
from sklearn.linear_model import LogisticRegression

### Importing dataset

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [3]:
dataset=pd.read_excel("/content/a_Dataset_CreditScoring.xlsx")

### Data preparation

# New Section

In [4]:
# shows count of rows and columns
dataset.shape

(3000, 30)

In [5]:
#shows first few rows of the code
dataset.head()

TARGET    ID  DerogCnt  CollectCnt  BanruptcyInd  InqCnt06  InqTimeLast  \
0       1   582         3           3             0         4          0.0   
1       1   662        15           9             0         3          1.0   
2       1   805         0           0             0         1          5.0   
3       1  1175         8           5             0         6          1.0   
4       1  1373         3           1             0         9          0.0   

   InqFinanceCnt24  TLTimeFirst  TLTimeLast  ...  TL50UtilCnt  TLBalHCPct  \
0                5          117          27  ...          3.0      0.9179   
1                3           14          14  ...          1.0      0.8000   
2                1          354           7  ...          5.0      0.3552   
3               10           16           4  ...          3.0      0.9127   
4                8          130          52  ...          1.0      1.2511   

   TLSatPct  TLDel3060Cnt24  TLDel90Cnt24  TLDel60CntAll  TLOpenPct  \
0    0.2083               2             3              7     0.2083   
1    0.0000               0             0              0     1.0000   
2    0.6538               0             1              1     0.7308   
3    0.2500               1             1              1     0.7500   
4    0.0000               0             1              4     0.1429   

   TLBadDerogCnt  TLDel60Cnt24  TLOpen24Pct  
0              4             4       0.0000  
1             12             0       1.0000  
2              1             1       0.5263  
3              7             1       1.3333  
4              3             1       0.0000  

[5 rows x 30 columns]

In [6]:
#dropping customer ID column from the dataset
dataset=dataset.drop('ID',axis=1)
dataset.shape

(3000, 29)

In [7]:
# explore missing values
dataset.isna().sum()

TARGET               0
DerogCnt             0
CollectCnt           0
BanruptcyInd         0
InqCnt06             0
InqTimeLast        188
InqFinanceCnt24      0
TLTimeFirst          0
TLTimeLast           0
TLCnt03              0
TLCnt12              0
TLCnt24              0
TLCnt                3
TLSum               40
TLMaxSum            40
TLSatCnt             4
TLDel60Cnt           0
TLBadCnt24           0
TL75UtilCnt         99
TL50UtilCnt         99
TLBalHCPct          41
TLSatPct             4
TLDel3060Cnt24       0
TLDel90Cnt24         0
TLDel60CntAll        0
TLOpenPct            3
TLBadDerogCnt        0
TLDel60Cnt24         0
TLOpen24Pct          3
dtype: int64

In [8]:
# filling missing values with mean
dataset=dataset.fillna(dataset.mean())

In [9]:
# explore missing values post missing value fix
dataset.isna().sum()

TARGET             0
DerogCnt           0
CollectCnt         0
BanruptcyInd       0
InqCnt06           0
InqTimeLast        0
InqFinanceCnt24    0
TLTimeFirst        0
TLTimeLast         0
TLCnt03            0
TLCnt12            0
TLCnt24            0
TLCnt              0
TLSum              0
TLMaxSum           0
TLSatCnt           0
TLDel60Cnt         0
TLBadCnt24         0
TL75UtilCnt        0
TL50UtilCnt        0
TLBalHCPct         0
TLSatPct           0
TLDel3060Cnt24     0
TLDel90Cnt24       0
TLDel60CntAll      0
TLOpenPct          0
TLBadDerogCnt      0
TLDel60Cnt24       0
TLOpen24Pct        0
dtype: int64

In [10]:
# # count of good loans (0) and bad loans (1)
# dataset['TARGET'].value_counts()

In [11]:
# # data summary across 0 & 1
# dataset.groupby('TARGET').mean()

### Train Test Split

In [12]:
y = dataset.iloc[:, 0].values
X = dataset.iloc[:, 1:29].values

In [13]:
# splitting dataset into training and test (in ratio 80:20)

X_train, X_test, y_train, y_test = train_test_split(X, y,
                                                    test_size=0.2,
                                                    random_state=0,
                                                    stratify=y)

In [14]:
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [15]:

# Exporting Normalisation Coefficients for later use in prediction
import joblib
joblib.dump(sc, '/content/f2_Normalisation_CreditScoring')

['/content/f2_Normalisation_CreditScoring']

### Risk Model building

In [16]:
classifier =  LogisticRegression()
classifier.fit(X_train, y_train)
y_pred = classifier.predict(X_test)

In [17]:
# Exporting Logistic Regression Classifier for later use in prediction

# import joblib
joblib.dump(classifier, '/content/f1_Classifier_CreditScoring')

['/content/f1_Classifier_CreditScoring']

### Model *performance*

In [18]:
print(confusion_matrix(y_test,y_pred))

[[487  13]
 [ 87  13]]


In [19]:
print(accuracy_score(y_test, y_pred))

0.8333333333333334


### Writing output file

In [20]:
predictions = classifier.predict_proba(X_test)
predictions

array([[0.61598311, 0.38401689],
       [0.98854759, 0.01145241],
       [0.87096661, 0.12903339],
       ...,
       [0.9445091 , 0.0554909 ],
       [0.46946796, 0.53053204],
       [0.94009714, 0.05990286]])

In [21]:
# writing model output file

df_prediction_prob = pd.DataFrame(predictions, columns = ['prob_0', 'prob_1'])
df_prediction_target = pd.DataFrame(classifier.predict(X_test), columns = ['predicted_TARGET'])
df_test_dataset = pd.DataFrame(y_test,columns= ['Actual Outcome'])

dfx=pd.concat([df_test_dataset, df_prediction_prob, df_prediction_target], axis=1)

dfx.to_csv("/content/c1_Model_Prediction.xlsx", sep=',', encoding='UTF-8')

dfx.head()

Actual Outcome    prob_0    prob_1  predicted_TARGET
0               1  0.615983  0.384017                 0
1               0  0.988548  0.011452                 0
2               1  0.870967  0.129033                 0
3               0  0.954084  0.045916                 0
4               1  0.726195  0.273805                 0

In [24]:
# prompt: by using the ensembling techniques improve the accuracy of the model

import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier, VotingClassifier
from sklearn.svm import SVC
from google.colab import drive
import joblib

# ... (Your existing code) ...

# ### Ensemble Methods
# Initialize the classifiers
clf1 = LogisticRegression()
clf2 = RandomForestClassifier(random_state=1)
clf3 = SVC(probability=True) # probability=True is required for predict_proba

# Create the ensemble model using VotingClassifier (soft voting)
ensemble_classifier = VotingClassifier(estimators=[('lr', clf1), ('rf', clf2), ('svc', clf3)], voting='soft')

# Train the ensemble model
ensemble_classifier.fit(X_train, y_train)

# Make predictions using the ensemble model
y_pred_ensemble = ensemble_classifier.predict(X_test)

# Evaluate the ensemble model
print("Ensemble Model Performance:")
print(confusion_matrix(y_test, y_pred_ensemble))
print(accuracy_score(y_test, y_pred_ensemble))

# Exporting Ensemble Classifier
joblib.dump(ensemble_classifier, '/content/f1_Ensemble_Classifier_CreditScoring')


# ### Writing output file for ensemble predictions
predictions_ensemble = ensemble_classifier.predict_proba(X_test)
df_prediction_prob_ensemble = pd.DataFrame(predictions_ensemble, columns = ['prob_0', 'prob_1'])
df_prediction_target_ensemble = pd.DataFrame(ensemble_classifier.predict(X_test), columns = ['predicted_TARGET'])

dfx_ensemble = pd.concat([df_test_dataset, df_prediction_prob_ensemble, df_prediction_target_ensemble], axis=1)
dfx_ensemble.to_csv("/content/c1_Ensemble_Model_Prediction.xlsx", sep=',', encoding='UTF-8')

dfx_ensemble.head()

Ensemble Model Performance:
[[489  11]
 [ 89  11]]
0.8333333333333334


Actual Outcome    prob_0    prob_1  predicted_TARGET
0               1  0.743261  0.256739                 0
1               0  0.951264  0.048736                 0
2               1  0.861893  0.138107                 0
3               0  0.951439  0.048561                 0
4               1  0.766240  0.233760                 0